### ISSUE TITLE
Update ffi-rzmq to 2

### ISSUE THREAD

**Issue by felipegs** [logstash-plugins/logstash-output-zeromq#1]
ffi-rzmq 1 use a very old version of libzmq, it would be nice if that were updated.

**Comment by driskell** [comment]
Yes. Log Courier can't install it's plugin anymore in Logstash 1.5 due to this. I believe it previously did but only because this plugin wasn't already installed. My plugin needs version 2.0.1 or above for the curve key functions.

CC: @electrical - would you accept a Pull Request for the following? Or could someone add it?

  s.add_runtime_dependency 'ffi-rzmq', ['=> 2.0.4', '~> 2.0.0']

This should allow version 2.0.4 (latest) and above, but allow newer versions that aren't a minor version change. How does this sound? I think with the release of Logstash 1.5 it's a better time if any to upgrade the dependency.

It is also worth noting that the logstash-input-zeromq plugin does NOT have a version requirement explicitly stated, and its only in this plugin where one appears to be.

I'd really like the Log Courier input plugin to work easily with Logstash 1.5 when it's released.

Thanks

**Comment by driskell** [comment]
https://github.com/driskell/logstash-input-zeromq/blob/master/logstash-input-zeromq.gemspec#L26 - no version dependency there. I can PR to mirror it to whatever we decide here.

**Comment by jc21** [comment]
+1

**Comment by ruddj** [comment]
Just adding a +1 to please add the version 2 dependency.

**Comment by jmreicha** [comment]
+1

**Comment by hinnerk** [comment]
Since ffi-rzmq has now entered maintenance mode, further updates to it should happen seldom and with long periods between them. So now is the perfect moment to switch to the current version. :)

**Comment by felipegs** [comment]
The logstash-output-zeromq should be update too.

**Comment by felipegs** [comment]
Maybe should be better to use `rbczmq`

`Most people writing Zeromq applications in Ruby should be using the rbczmq project. It wraps the CZMQ binding which is a much higher-level library for writing Zeromq code` extracted from https://github.com/chuckremes/ffi-rzmq

**Comment by suyograo** [comment]
@driskell thanks for bringing this up. Could you provide a PR for this?

**Comment by driskell** [comment]
@felipegs rbczmq looks like it doesn't support JRuby yet so that switch won't happen. The FFI bindings do. I also question the wisdom in packaging in ZeroMQ with the rbczmq gem. Although simpler to install it means you then rely on rbczmq to provide you with ZeroMQ fixes, including security fixes which seems to me a hidden blur of responsibilities.

@suyograo Thanks! I'll throw one across shortly.

**Comment by matejzero** [comment]
+1 from me too...

**Comment by nopslip** [comment]
+1

**Comment by driskell** [comment]
Will have a PR tonight. I've been battling with Logstash bundler and local .gem files to try test updating! Think I've got it wrapped. I'll raise an issue on Logstash repo when done regarding the plugin manager issues (mainly minor and related to .gem files) and can PR there too if help required.

**Comment by felipegs** [comment]
@driskell Could you take a look at logstash-input-zeromq ffi-rzmq version too?

**Comment by mareklobaza** [comment]
1+

**Comment by driskell** [comment]
I've raised PR for both plugins. Thanks @suyograo

**Comment by suyograo** [comment]
Thanks @driskell. I published new versions of the plugins to RubyGems.

**Comment by mareklobaza** [comment]
Confirmed - new version (0.1.5) is available on RubyGems with updated ffi-zrmq lib
